## Mathematics for AI

### Linear Algebra

In [ ]:
#Scalar
import numpy as np
scalar = np.array(10)
print("Scalar:", scalar)
print("Shape:",scalar.shape)
print("Dimensions:",scalar.ndim)

Scalar: 10
Shape: ()
Dimensions: 0


In [ ]:
#Vector
import numpy as np
vector = np.array([10,20,30,40,50])
print("Vector:", vector)
print("Shape:",vector.shape)
print("Dimensions:",vector.ndim)

Vector: [10 20 30 40 50]
Shape: (5,)
Dimensions: 1


In [ ]:
#Matrix
import numpy as np
matrix = np.array([[10,20],[30,60],[40,80]])
print("Matrix:",matrix)
print("Shape:",matrix.shape)
print("Dimension:",matrix.ndim)

Matrix: [[10 20]
 [30 60]
 [40 80]]
Shape: (3, 2)
Dimension: 2


In [ ]:
#Tensor
import numpy as np
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Tensor:",tensor)
print("Shape:",tensor.shape)
print("Dimension:",tensor.ndim)

Tensor: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Dimension: 3


In [ ]:
#Matrix Addition, Subtraction, Multiplication and Division
import numpy as np
a = np.array([[4,2],[3,6]])
b = np.array([[4,8],[7,3]])
c = a+b
d = a-b
e = a @ b
f = a/b
print("Matrix A:",a)
print("\nMatrix B:",b)
print("\nMatrix c:",c)
print("\nMatrix d:",d)
print("\nMatrix e:",e)
print("\nMatrix f:",f)

Matrix A: [[4 2]
 [3 6]]

Matrix B: [[4 8]
 [7 3]]

Matrix c: [[ 8 10]
 [10  9]]

Matrix d: [[ 0 -6]
 [-4  3]]

Matrix e: [[30 38]
 [54 42]]

Matrix f: [[1.         0.25      ]
 [0.42857143 2.        ]]


In [ ]:
#Matrix Multiplication using np.dot()
import numpy as np
a = np.array([[4,2],[3,6]])
b = np.array([[4,8],[7,3]])
c = np.dot(a,b)
print ("Matrix c:",c)

Matrix c: [[30 38]
 [54 42]]


In [ ]:
#Transpose of a Matrix
import numpy as np
a = np.array([[3,4,5],[6,7,8]])
print(a)
print()
print(a.T)

[[3 4 5]
 [6 7 8]]

[[3 6]
 [4 7]
 [5 8]]


In [ ]:
#Identity matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Eigenvalues and Eigenvectots
import numpy as np

# Step 1: Create the matrix
A = np.array([
    [4, 2],
    [1, 3]
])

# Step 2: Find eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Step 3: Print the matrix
print("Matrix:")
print(A)

# Step 4: Print eigenvalues
print("\nEigenvalues:")
print(eigenvalues)

# Step 5: Print eigenvectors
print("\nEigenvectors:")
print(eigenvectors)

# Step 6: Verify the first eigenvector
v1 = eigenvectors[:, 0]
lambda1 = eigenvalues[0]

print("\nA @ v1:")
print(A @ v1)

print("\nlambda1 * v1:")
print(lambda1 * v1)

Matrix:
[[4 2]
 [1 3]]

Eigenvalues:
[5.+0.j 2.+0.j]

Eigenvectors:
[[ 0.89442719+0.j -0.70710678+0.j]
 [ 0.4472136 +0.j  0.70710678+0.j]]

A @ v1:
[4.47213595+0.j 2.23606798+0.j]

lambda1 * v1:
[4.47213595+0.j 2.23606798+0.j]


In [26]:
import numpy as np
A = np.array([[1,2],[3,4]])
eigenvalues,eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

v1=eigenvectors[:,0]
lambda1=eigenvalues[0]

print("\nA@v1:")
print(A@v1)
print("\nlamba1*v1:")
print(lambda1*v1)


Eigenvalues:
[-0.37228132+0.j  5.37228132+0.j]

Eigenvectors:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]

A@v1:
[ 0.30697009+0.j -0.21062466+0.j]

lamba1*v1:
[ 0.30697009-0.j -0.21062466+0.j]


In [28]:
import numpy as np
A = np.array([
    [6, 2],
    [2, 3]
])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

v2=eigenvectors[:,1]
lambda2=eigenvalues[1]
print("\nA@v2")
print(A@v2)
print("\nlambda2*v2")
print(lambda2*v2)




Eigenvalues:
[7.+0.j 2.+0.j]

Eigenvectors:
[[ 0.89442719+0.j -0.4472136 +0.j]
 [ 0.4472136 +0.j  0.89442719+0.j]]

A@v2
[-0.89442719+0.j  1.78885438+0.j]

lambda2*v2
[-0.89442719+0.j  1.78885438+0.j]


## Probability

In [ ]:
import random
roll = random.randint(1,6)
print("You rolled:",roll)

You rolled: 2


In [43]:
import random
rolls = 100000

count_three = 0
count_even = 0
count_greater_than_4 = 0

for i in range(rolls):
    roll = random.randint(1, 6)

    if roll == 3:
        count_three += 1

    if roll % 2 == 0:
        count_even += 1

    if roll > 4:
        count_greater_than_4 += 1

print("Probability of rolling 3:", count_three / rolls)
print("Probability of rolling an even number:", count_even / rolls)
print("Probability of rolling a number greater than 4:", count_greater_than_4 / rolls)

Probability of rolling 3: 0.16574
Probability of rolling an even number: 0.50003
Probability of rolling a number greater than 4: 0.33382


In [44]:
import random
print("Rolling a dice  times")
for i in range(20):
    roll=random.randint(1,6)
    print("Rolls",i+1,"=",roll)
    if roll % 2 == 0:
        print("-> Event occured(even number)")

Rolling a dice  times
Rolls 1 = 1
Rolls 2 = 4
-> Event occured(even number)
Rolls 3 = 5
Rolls 4 = 3
Rolls 5 = 3
Rolls 6 = 3
Rolls 7 = 2
-> Event occured(even number)
Rolls 8 = 6
-> Event occured(even number)
Rolls 9 = 5
Rolls 10 = 3
Rolls 11 = 1
Rolls 12 = 4
-> Event occured(even number)
Rolls 13 = 4
-> Event occured(even number)
Rolls 14 = 2
-> Event occured(even number)
Rolls 15 = 3
Rolls 16 = 4
-> Event occured(even number)
Rolls 17 = 3
Rolls 18 = 5
Rolls 19 = 2
-> Event occured(even number)
Rolls 20 = 2
-> Event occured(even number)


In [ ]:
#Bayes Theorm

# Prior probability of disease
P_Disease = 10 / 1000

# Probability of testing positive if disease exists
P_Positive_given_Disease = 0.99

# Probability of testing positive
P_Positive = ((10 * 0.99) + (990 * 0.05)) / 1000

# Bayes' Theorem
P_Disease_given_Positive = (
    P_Positive_given_Disease * P_Disease
) / P_Positive

print("Probability of Disease given Positive Test:")
print(P_Disease_given_Positive)

Probability of Disease given Positive Test:
0.16666666666666669


In [46]:
# Probabilities
P_spam = 0.20
P_not_spam = 0.80

P_marked_given_spam = 0.95
P_marked_given_not_spam = 0.10

# Probability that an email is marked as spam
P_marked = (
    P_marked_given_spam * P_spam
) + (
    P_marked_given_not_spam * P_not_spam
)

# Bayes' Theorem
P_spam_given_marked = (
    P_marked_given_spam * P_spam
) / P_marked

print("Probability an email is marked as spam:", P_marked)
print("Probability an email is actually spam given it was marked as spam:", P_spam_given_marked)

Probability an email is marked as spam: 0.27
Probability an email is actually spam given it was marked as spam: 0.7037037037037037
