## Data Analysis

### Numpy Array

In [1]:
import numpy as np
numbers = np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [2]:
import numpy as np
marks = np.array([25,35,45,55])
print(marks+5)

[30 40 50 60]


In [3]:
import numpy as np
marks = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(marks)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
import numpy as np

marks = np.array([78, 85, 90, 95, 88])

print("Array:", marks)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Dimensions:", marks.ndim)
print("Datatype:", marks.dtype)

Array: [78 85 90 95 88]
Shape: (5,)
Size: 5
Dimensions: 1
Datatype: int64


In [6]:
import numpy as np

arr = np.array([5,10,15,20,25,30])

print("First:", arr[0])
print("Last:", arr[-1])
print("Middle:", arr[2])

print("Slice:", arr[1:5])
print("Every second:", arr[::2])
print("Reverse:", arr[::-1])

First: 5
Last: 30
Middle: 15
Slice: [10 15 20 25]
Every second: [ 5 15 25]
Reverse: [30 25 20 15 10  5]


In [7]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr + 5)
print(arr - 5)
print(arr * 2)
print(arr / 10)
print(arr ** 2)

[15 25 35 45 55]
[ 5 15 25 35 45]
[ 20  40  60  80 100]
[1. 2. 3. 4. 5.]
[ 100  400  900 1600 2500]


In [8]:
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A + B)
print(A - B)
print(B / A)
print(A @ B)

[5 7 9]
[-3 -3 -3]
[4.  2.5 2. ]
32


In [ ]:
arr = np.array([4,9,16,25])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

angles = np.array([0,30,45,60,90])

print(np.sin(np.radians(angles)))

[2. 3. 4. 5.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]
[1.38629436 2.19722458 2.77258872 3.21887582]


In [12]:
# Aggregation Functions
arr = np.array([10,20,30,40,50])
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

50
10
150
30.0
30.0
14.142135623730951


In [13]:
#Broadcasting
A = np.array([
    [1],
    [2],
    [3]
])

B = np.array([10,20,30])

print(A + B)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [14]:
import numpy as np

arr = np.array([5,10,15,20])

print("Original:", arr)
print("Add 5:", arr + 5)
print("Multiply by 3:", arr * 3)
print("Square:", arr ** 2)

print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

Original: [ 5 10 15 20]
Add 5: [10 15 20 25]
Multiply by 3: [15 30 45 60]
Square: [ 25 100 225 400]
Maximum: 20
Minimum: 5
Sum: 50
Mean: 12.5


In [16]:
#Creating a Dataframe using pandas
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 21, 22],
    "Marks": [90, 85, 95]
}

df = pd.DataFrame(data)

print(df)

      Name  Age  Marks
0    Alice   20     90
1      Bob   21     85
2  Charlie   22     95


In [ ]:
#dataframe rows
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 21, 22],
    "Marks": [90, 85, 95]
}
df = pd.DataFrame(data)
print(df.head(2))

    Name  Age  Marks
0  Alice   20     90
1    Bob   21     85


In [ ]:
#dataframe columns
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 21, 22],
    "Marks": [90, 85, 95]
}
df = pd.DataFrame(data)
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='str')


In [20]:
#columns as list
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 21, 22],
    "Marks": [90, 85, 95]
}
df = pd.DataFrame(data)
print(df.columns.tolist())

['Name', 'Age', 'Marks']


In [21]:
#datatypes of columns
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 21, 22],
    "Marks": [90, 85, 95]
}
df = pd.DataFrame(data)
print(df.dtypes)

Name       str
Age      int64
Marks    int64
dtype: object


In [22]:
#Information About Dataset
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 21, 22],
    "Marks": [90, 85, 95]
}
df = pd.DataFrame(data)
df.info()


<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str  
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes


In [25]:
#Access One and multiple Columns
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 21, 22],
    "Marks": [90, 85, 95]
}
df = pd.DataFrame(data)
print(df["Name"])
print(df["Marks"])
print(df[["Name", "Marks"]])
df["Grade"] = ["A", "B", "A"] # adding new column
df = df.drop("Grade", axis=1) #Deleting a Column
df.rename(columns={"Marks": "Score"}) #Renaming Columns
print(df)

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str
0    90
1    85
2    95
Name: Marks, dtype: int64
      Name  Marks
0    Alice     90
1      Bob     85
2  Charlie     95
      Name  Age  Marks
0    Alice   20     90
1      Bob   21     85
2  Charlie   22     95


In [26]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 22, 23],
    "Marks": [90, 85, 95, 88]
}

df = pd.DataFrame(data)

print(df)

print(df.head())

print(df.tail(2))

print(df.shape)

print(df.columns)

print(df.dtypes)

print(df.describe())

print(df["Marks"])

df["Grade"] = ["A", "B", "A", "B"]

print(df)

      Name  Age  Marks
0    Alice   20     90
1      Bob   21     85
2  Charlie   22     95
3    David   23     88
      Name  Age  Marks
0    Alice   20     90
1      Bob   21     85
2  Charlie   22     95
3    David   23     88
      Name  Age  Marks
2  Charlie   22     95
3    David   23     88
(4, 3)
Index(['Name', 'Age', 'Marks'], dtype='str')
Name       str
Age      int64
Marks    int64
dtype: object
             Age      Marks
count   4.000000   4.000000
mean   21.500000  89.500000
std     1.290994   4.203173
min    20.000000  85.000000
25%    20.750000  87.250000
50%    21.500000  89.000000
75%    22.250000  91.250000
max    23.000000  95.000000
0    90
1    85
2    95
3    88
Name: Marks, dtype: int64
      Name  Age  Marks Grade
0    Alice   20     90     A
1      Bob   21     85     B
2  Charlie   22     95     A
3    David   23     88     B


In [28]:
#reading csv file
import pandas as pd

df = pd.read_csv("students.csv")
print(df)
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

      Name  Age  Marks       City
0    Alice   20     90      Delhi
1      Bob   21     85     Mumbai
2  Charlie   22     95    Chennai
3    David   23     88  Bangalore
4      Eva   20     91  Hyderabad
      Name  Age  Marks       City
0    Alice   20     90      Delhi
1      Bob   21     85     Mumbai
2  Charlie   22     95    Chennai
3    David   23     88  Bangalore
4      Eva   20     91  Hyderabad
      Name  Age  Marks       City
0    Alice   20     90      Delhi
1      Bob   21     85     Mumbai
2  Charlie   22     95    Chennai
3    David   23     88  Bangalore
4      Eva   20     91  Hyderabad
(5, 4)
Index(['Name', 'Age', 'Marks', 'City'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str  
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
 3   City    5 non-null      str  
dtypes: int64(2), str(2)
memo

In [29]:
#filtering data
import pandas as pd

df = pd.read_csv("students.csv")

print(df)

#Selecting a Single Column
print(df["Name"])

#Selecting Multiple Columns
print(df[["Name", "Marks"]])

#filter rows
print(df[df["Marks"] > 90]) #Students with Marks > 90
print(df[df["Marks"] >= 90]) #Students with Marks >= 90
print(df[df["Age"] < 22]) #Students with Age < 22
print(df[df["City"] == "Delhi"]) #Students from Delhi
print(df[df["City"] != "Delhi"]) #Students not from Delhi
print(df[(df["Age"] > 20) & (df["Marks"] > 85)]) #Multiple Conditions (AND)
print(df[(df["City"] == "Delhi") | (df["Marks"] > 90)]) #Multiple Conditions (OR)
print(df[df["City"].isin(["Delhi", "Mumbai"])]) #Filter Using isin()
print(df.sort_values("Marks")) #sorting data, ascending order
print(df.sort_values("Marks", ascending=False)) #sorting data, descending order
print(df.sort_values(["Age", "Marks"])) #Sort by Multiple Columns
top_students = df.sort_values("Marks", ascending=False)

print(top_students.head(3)) #selecting top 3 students based on marks

      Name  Age  Marks       City
0    Alice   20     90      Delhi
1      Bob   21     85     Mumbai
2  Charlie   22     95    Chennai
3    David   23     88  Bangalore
4      Eva   20     91  Hyderabad
0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: str
      Name  Marks
0    Alice     90
1      Bob     85
2  Charlie     95
3    David     88
4      Eva     91
      Name  Age  Marks       City
2  Charlie   22     95    Chennai
4      Eva   20     91  Hyderabad
      Name  Age  Marks       City
0    Alice   20     90      Delhi
2  Charlie   22     95    Chennai
4      Eva   20     91  Hyderabad
    Name  Age  Marks       City
0  Alice   20     90      Delhi
1    Bob   21     85     Mumbai
4    Eva   20     91  Hyderabad
    Name  Age  Marks   City
0  Alice   20     90  Delhi
      Name  Age  Marks       City
1      Bob   21     85     Mumbai
2  Charlie   22     95    Chennai
3    David   23     88  Bangalore
4      Eva   20     91  Hyderabad
      Na

In [30]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df[df["Marks"] > 85])

print(df[df["Age"] == 20])

print(df[(df["Age"] > 20) & (df["Marks"] > 85)])

print(df.sort_values("Marks", ascending=False))

print(df[df["City"].isin(["Delhi", "Chennai"])])

      Name  Age  Marks       City
0    Alice   20     90      Delhi
2  Charlie   22     95    Chennai
3    David   23     88  Bangalore
4      Eva   20     91  Hyderabad
    Name  Age  Marks       City
0  Alice   20     90      Delhi
4    Eva   20     91  Hyderabad
      Name  Age  Marks       City
2  Charlie   22     95    Chennai
3    David   23     88  Bangalore
      Name  Age  Marks       City
2  Charlie   22     95    Chennai
4      Eva   20     91  Hyderabad
0    Alice   20     90      Delhi
3    David   23     88  Bangalore
1      Bob   21     85     Mumbai
      Name  Age  Marks     City
0    Alice   20     90    Delhi
2  Charlie   22     95  Chennai


In [32]:
# groupBy
# create a dataframe
import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "Sales", "HR", "Sales"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Salary": [50000, 40000, 60000, 70000, 45000, 75000]
}

df = pd.DataFrame(data)
print(df.groupby("Department")) #grouping by department
print(df.groupby("Department")["Salary"].mean()) #average salary by department
print(df.groupby("Department")["Salary"].sum()) #sum
print(df.groupby("Department")["Salary"].count()) #count
print(df.groupby("Department")["Salary"].max()) #maximum salary
print(df.groupby("Department")["Salary"].min()) #minimum salary
print(df.groupby("Department")["Salary"].median()) #median salary by department
print(
    df.groupby("Department")["Salary"].agg(
        ["mean", "sum", "max", "min", "count"]
    )
) #multiple aggregations
data = {
    "Department": ["IT", "IT", "HR", "HR", "Sales", "Sales"],
    "Gender": ["F", "M", "M", "F", "M", "F"],
    "Salary": [50000, 60000, 40000, 45000, 70000, 75000]
}

df = pd.DataFrame(data) #group by multiple columns
avg_salary = df.groupby("Department")["Salary"].mean()

print(avg_salary) #reset index

print(df)

Department
HR       42500.0
IT       55000.0
Sales    72500.0
Name: Salary, dtype: float64
Department
HR        85000
IT       110000
Sales    145000
Name: Salary, dtype: int64
Department
HR       2
IT       2
Sales    2
Name: Salary, dtype: int64
Department
HR       45000
IT       60000
Sales    75000
Name: Salary, dtype: int64
Department
HR       40000
IT       50000
Sales    70000
Name: Salary, dtype: int64
Department
HR       42500.0
IT       55000.0
Sales    72500.0
Name: Salary, dtype: float64
               mean     sum    max    min  count
Department                                      
HR          42500.0   85000  45000  40000      2
IT          55000.0  110000  60000  50000      2
Sales       72500.0  145000  75000  70000      2
Department
HR       42500.0
IT       55000.0
Sales    72500.0
Name: Salary, dtype: float64
  Department Gender  Salary
0         IT      F   50000
1         IT      M   60000
2         HR      M   40000
3         HR      F   45000
4      Sales      M

In [33]:
import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "Sales", "HR", "Sales"],
    "Salary": [50000, 40000, 60000, 70000, 45000, 75000]
}

df = pd.DataFrame(data)

print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Department")["Salary"].sum())
print(df.groupby("Department")["Salary"].count())
print(df.groupby("Department")["Salary"].max())
print(df.groupby("Department")["Salary"].min())

Department
HR       42500.0
IT       55000.0
Sales    72500.0
Name: Salary, dtype: float64
Department
HR        85000
IT       110000
Sales    145000
Name: Salary, dtype: int64
Department
HR       2
IT       2
Sales    2
Name: Salary, dtype: int64
Department
HR       45000
IT       60000
Sales    75000
Name: Salary, dtype: int64
Department
HR       40000
IT       50000
Sales    70000
Name: Salary, dtype: int64


In [35]:
#Missing Value Handling(NaN)
#Create a DataFrame with Missing Values
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, np.nan, 22, 24],
    "Marks": [90, 85, np.nan, 95]
}

df = pd.DataFrame(data)
print(df.isnull())  #checking for missing values
print(df.isnull().sum()) #count missing values
clean_df = df.dropna()

print(clean_df) #remove rows with missing values
df.dropna(axis=1) #remove columns with missing values
df.fillna(0) #fill missing values with constant
df["Age"] = df["Age"].fillna(df["Age"].mean())

print(df) #fill missing values with mean 
df["Marks"] = df["Marks"].fillna(df["Marks"].median()) #fill missing values with median
df.ffill() #forward fill(ffill)
df.bfill() #backward fill(bfill)
print(df.isnull().sum()) #check if any missing values remain


print(df)

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
Name     0
Age      1
Marks    1
dtype: int64
    Name   Age  Marks
0  Alice  20.0   90.0
3  David  24.0   95.0
      Name   Age  Marks
0    Alice  20.0   90.0
1      Bob  22.0   85.0
2  Charlie  22.0    NaN
3    David  24.0   95.0
Name     0
Age      0
Marks    0
dtype: int64
      Name   Age  Marks
0    Alice  20.0   90.0
1      Bob  22.0   85.0
2  Charlie  22.0   90.0
3    David  24.0   95.0


In [36]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, np.nan, 22, 24],
    "Marks": [90, 85, np.nan, 95]
}

df = pd.DataFrame(data)

print("Original Data:")
print(df)

print("\nMissing Values:")
print(df.isnull().sum())

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Marks"] = df["Marks"].fillna(df["Marks"].median())

print("\nCleaned Data:")
print(df)

print("\nRemaining Missing Values:")
print(df.isnull().sum())

Original Data:
      Name   Age  Marks
0    Alice  20.0   90.0
1      Bob   NaN   85.0
2  Charlie  22.0    NaN
3    David  24.0   95.0

Missing Values:
Name     0
Age      1
Marks    1
dtype: int64

Cleaned Data:
      Name   Age  Marks
0    Alice  20.0   90.0
1      Bob  22.0   85.0
2  Charlie  22.0   90.0
3    David  24.0   95.0

Remaining Missing Values:
Name     0
Age      0
Marks    0
dtype: int64


In [37]:
# data preprocessing
#Remove Duplicate Rows
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Marks": [90, 85, 90, 95]
}

df = pd.DataFrame(data)

print(df)

#rename columns
df.rename(columns={"Marks": "Score"}, inplace=True)

print(df)

#change data type
print(df.dtypes)
df["Score"] = df["Score"].astype(float)
df["Score"] = df["Score"].astype(int)
df["Score"] = df["Score"].astype(str)

#Create New Columns
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Marks": [90, 35, 70]
}

df = pd.DataFrame(data)

#string operations
df["Name"] = df["Name"].str.upper()
df["Name"] = df["Name"].str.lower()
df["Name"] = df["Name"].str.title()
df["Name"] = df["Name"].str.strip()

#basic encoding
df["Gender"] = df["Gender"].map({
    "Male":1,
    "Female":0
})

    Name  Marks
0  Alice     90
1    Bob     85
2  Alice     90
3  David     95
    Name  Score
0  Alice     90
1    Bob     85
2  Alice     90
3  David     95
Name       str
Score    int64
dtype: object


KeyError: 'Gender'

In [38]:
import pandas as pd

data = {
    "Name": ["Alice","Bob","Alice","David"],
    "Marks":[90,35,90,95]
}

df = pd.DataFrame(data)

df = df.drop_duplicates()

df.rename(columns={"Marks":"Score"}, inplace=True)

df["Pass"] = df["Score"] >= 40

df["Name"] = df["Name"].str.upper()

print(df)

    Name  Score   Pass
0  ALICE     90   True
1    BOB     35  False
3  DAVID     95   True


## feature Engineering basics


In [40]:
#bmi calculation
import pandas as pd

data = {
    "Height":[170,160,180],
    "Weight":[70,60,90]
}

df = pd.DataFrame(data)
df["BMI"] = df["Weight"] / ((df["Height"]/100)**2)

print(df)

   Height  Weight        BMI
0     170      70  24.221453
1     160      60  23.437500
2     180      90  27.777778


In [45]:
#bonus
data = {
    "Employee":["A","B","C"],
    "Salary":[40000,50000,60000]
}

df = pd.DataFrame(data)

df["Bonus"] = df["Salary"] * 0.10
# total marks
data = {
    "Math":[80,90,75],
    "Science":[70,95,85]
}

df = pd.DataFrame(data)

df["Total"] = df["Math"] + df["Science"]
#Averge Marks
df["Average"] = (df["Math"] + df["Science"]) / 2
#pass/fail
df["Pass"] = df["Average"] >= 40
print(df)

   Math  Science  Total  Average  Pass
0    80       70    150     75.0  True
1    90       95    185     92.5  True
2    75       85    160     80.0  True


In [46]:
import pandas as pd

data = {
    "Math":[80,60,95],
    "Science":[70,75,90]
}

df = pd.DataFrame(data)

df["Total"] = df["Math"] + df["Science"]

df["Average"] = df["Total"] / 2

df["Pass"] = df["Average"] >= 40

print(df)

   Math  Science  Total  Average  Pass
0    80       70    150     75.0  True
1    60       75    135     67.5  True
2    95       90    185     92.5  True
